name: PunishGUI
version: 1.0.8
main: net.bghddevelopment.punishmentgui.PunishGUI
authors: BGHDDevelopment LLC
softdepend:
  - PlaceholderAPI
  - HeadDatabase
description: PunishmentGUI which supports LiteBans, AdvancedBan, and many others.
website: https://bghddevelopment.com

