name: PunishGUI
version: 1.0.9
main: net.bghddevelopment.punishmentgui.PunishGUI
authors: [BGHDDevelopment LLC]
api-version: "1.13"
softdepend:
  - PlaceholderAPI
  - HeadDatabase
  - Skulls
description: PunishmentGUI which supports LiteBans, AdvancedBan, and many others.
website: https://bghddevelopment.com