name: PunishGUI
version: 1.0.3
main: net.bghddevelopment.punishmentgui.PunishGUI
authors: [BGHDDevelopment]
softdepend:
  - PlaceholderAPI
description: PunishmentGUI which supports LiteBans, AdvancedBan, and many others.
website: https://bghddevelopment.com

