name: PunishGUI
version: 1.1.11
main: net.bghddevelopment.punishmentgui.PunishGUI
author: BGHDDevelopmentLLC
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - HeadDatabase
  - Skulls
description: PunishmentGUI which supports LiteBans, AdvancedBan, and many others.
website: https://bghddevelopment.com